export default {
  COVID_DAILY_DATE_API: process.env.REACT_APP_COVID_DAILY_DATA_API,
  COVID_GLOBAL_TOTALS_API: process.env.REACT_APP_COVID_GLOBAL_TOTALS_API,
  COVID_COUNTRY_HISTORICAL_API: process.env.REACT_APP_COVID_HISTORICAL_DATA_API,
};
