// Export Array of Country objects
export default {
  countries2: [
    {
      name: 'Australia',
      slug: 'australia',
      ISO2: 'AU',
      continent: 'Oceania',
    },
  ],
  countries: [
    {
      name: 'Lao PDR',
      slug: 'lao-pdr',
      ISO2: 'LA',
      continent: 'Asia',
    },
    {
      name: 'Palestinian Territory',
      slug: 'palestine',
      ISO2: 'PS',
      continent: 'Asia',
    },
    {
      name: 'Australia',
      slug: 'australia',
      ISO2: 'AU',
      continent: 'Oceania',
    },
    {
      name: 'Bahrain',
      slug: 'bahrain',
      ISO2: 'BH',
      continent: 'Asia',
    },
    {
      name: 'Cambodia',
      slug: 'cambodia',
      ISO2: 'KH',
      continent: 'Asia',
    },
    {
      name: 'Canada',
      slug: 'canada',
      ISO2: 'CA',
      continent: 'North America',
    },
    {
      name: 'Dominican Republic',
      slug: 'dominican-republic',
      ISO2: 'DO',
      continent: 'North America',
    },
    {
      name: 'Sao Tome and Principe',
      slug: 'sao-tome-and-principe',
      ISO2: 'ST',
      continent: 'Africa',
    },
    {
      name: 'Congo (Brazzaville)',
      slug: 'congo-brazzaville',
      ISO2: 'CG',
      continent: 'Africa',
    },
    {
      name: 'Ethiopia',
      slug: 'ethiopia',
      ISO2: 'ET',
      continent: 'Africa',
    },
    {
      name: 'Mauritius',
      slug: 'mauritius',
      ISO2: 'MU',
      continent: 'Africa',
    },
    {
      name: 'Denmark',
      slug: 'denmark',
      ISO2: 'DK',
      continent: 'Europe',
    },
    {
      name: 'El Salvador',
      slug: 'el-salvador',
      ISO2: 'SV',
      continent: 'South America',
    },
    {
      name: 'Trinidad and Tobago',
      slug: 'trinidad-and-tobago',
      ISO2: 'TT',
      continent: 'North America',
    },
    {
      name: 'Chad',
      slug: 'chad',
      ISO2: 'TD',
      continent: 'Africa',
    },
    {
      name: 'Seychelles',
      slug: 'seychelles',
      ISO2: 'SC',
      continent: 'Africa',
    },
    {
      name: 'Afghanistan',
      slug: 'afghanistan',
      ISO2: 'AF',
      continent: 'Asia',
    },
    {
      name: 'Korea (South)',
      slug: 'korea-south',
      ISO2: 'KR',
      continent: 'Asia',
    },
    {
      name: 'South Sudan',
      slug: 'south-sudan',
      ISO2: 'SS',
      continent: 'Africa',
    },
    {
      name: 'Venezuela (Bolivarian Republic)',
      slug: 'venezuela',
      ISO2: 'VE',
      continent: 'South America',
    },
    {
      name: 'Argentina',
      slug: 'argentina',
      ISO2: 'AR',
      continent: 'South America',
    },
    {
      name: 'Aruba',
      slug: 'aruba',
      ISO2: 'AW',
      continent: 'North America',
    },
    {
      name: 'Bahamas',
      slug: 'bahamas',
      ISO2: 'BS',
      continent: 'North America',
    },
    {
      name: 'Hungary',
      slug: 'hungary',
      ISO2: 'HU',
      continent: 'Europe',
    },
    {
      name: 'Kuwait',
      slug: 'kuwait',
      ISO2: 'KW',
      continent: 'Asia',
    },
    {
      name: 'Mauritania',
      slug: 'mauritania',
      ISO2: 'MR',
      continent: 'Africa',
    },
    {
      name: 'Nepal',
      slug: 'nepal',
      ISO2: 'NP',
      continent: 'Asia',
    },
    {
      name: 'Sri Lanka',
      slug: 'sri-lanka',
      ISO2: 'LK',
      continent: 'Asia',
    },
    {
      name: 'Brazil',
      slug: 'brazil',
      ISO2: 'BR',
      continent: 'South America',
    },
    {
      name: 'Cameroon',
      slug: 'cameroon',
      ISO2: 'CM',
      continent: 'Africa',
    },
    {
      name: 'Chile',
      slug: 'chile',
      ISO2: 'CL',
      continent: 'South America',
    },
    {
      name: 'Jamaica',
      slug: 'jamaica',
      ISO2: 'JM',
      continent: 'North America',
    },
    {
      name: 'Uganda',
      slug: 'uganda',
      ISO2: 'UG',
      continent: 'Africa',
    },
    {
      name: 'Equatorial Guinea',
      slug: 'equatorial-guinea',
      ISO2: 'GQ',
      continent: 'Africa',
    },
    {
      name: 'Faroe Islands',
      slug: 'faroe-islands',
      ISO2: 'FO',
      continent: 'Europe',
    },
    {
      name: 'Macedonia, Republic of',
      slug: 'macedonia',
      ISO2: 'MK',
      continent: 'Europe',
    },
    {
      name: 'Philippines',
      slug: 'philippines',
      ISO2: 'PH',
      continent: 'Asia',
    },
    {
      name: 'Taiwan, Republic of China',
      slug: 'taiwan',
      ISO2: 'TW',
      continent: 'Asia',
    },
    {
      name: 'Paraguay',
      slug: 'paraguay',
      ISO2: 'PY',
      continent: 'South America',
    },
    {
      name: 'Somalia',
      slug: 'somalia',
      ISO2: 'SO',
      continent: 'Africa',
    },
    {
      name: 'Azerbaijan',
      slug: 'azerbaijan',
      ISO2: 'AZ',
      continent: 'Asia',
    },
    {
      name: 'Cuba',
      slug: 'cuba',
      ISO2: 'CU',
      continent: 'North America',
    },
    {
      name: 'Niger',
      slug: 'niger',
      ISO2: 'NE',
      continent: 'Africa',
    },
    {
      name: 'Belarus',
      slug: 'belarus',
      ISO2: 'BY',
      continent: 'Europe',
    },
    {
      name: 'South Africa',
      slug: 'south-africa',
      ISO2: 'ZA',
      continent: 'Africa',
    },
    {
      name: 'Vanuatu',
      slug: 'vanuatu',
      ISO2: 'VU',
      continent: 'Oceania',
    },
    {
      name: 'Angola',
      slug: 'angola',
      ISO2: 'AO',
      continent: 'Africa',
    },
    {
      name: 'Armenia',
      slug: 'armenia',
      ISO2: 'AM',
      continent: 'Asia',
    },
    {
      name: 'Cyprus',
      slug: 'cyprus',
      ISO2: 'CY',
      continent: 'Asia',
    },
    {
      name: 'Djibouti',
      slug: 'djibouti',
      ISO2: 'DJ',
      continent: 'Africa',
    },
    {
      name: 'French Polynesia',
      slug: 'french-polynesia',
      ISO2: 'PF',
      continent: 'Oceania',
    },
    {
      name: 'Guadeloupe',
      slug: 'guadeloupe',
      ISO2: 'GP',
      continent: 'North America',
    },
    {
      name: 'Honduras',
      slug: 'honduras',
      ISO2: 'HN',
      continent: 'North America',
    },
    {
      name: 'Nigeria',
      slug: 'nigeria',
      ISO2: 'NG',
      continent: 'Africa',
    },
    {
      name: 'Sweden',
      slug: 'sweden',
      ISO2: 'SE',
      continent: 'Europe',
    },
    {
      name: 'United Arab Emirates',
      slug: 'united-arab-emirates',
      ISO2: 'AE',
      continent: 'Asia',
    },
    {
      name: 'Zambia',
      slug: 'zambia',
      ISO2: 'ZM',
      continent: 'Africa',
    },
    {
      name: 'Comoros',
      slug: 'comoros',
      ISO2: 'KM',
      continent: 'Africa',
    },
    {
      name: 'Dominica',
      slug: 'dominica',
      ISO2: 'DM',
      continent: 'North America',
    },
    {
      name: 'Guatemala',
      slug: 'guatemala',
      ISO2: 'GT',
      continent: 'North America',
    },
    {
      name: 'Timor-Leste',
      slug: 'timor-leste',
      ISO2: 'TL',
      continent: 'Asia',
    },
    {
      name: 'Turks and Caicos Islands',
      slug: 'turks-and-caicos-islands',
      ISO2: 'TC',
      continent: 'North America',
    },
    {
      name: 'Eritrea',
      slug: 'eritrea',
      ISO2: 'ER',
      continent: 'Africa',
    },
    {
      name: 'Panama',
      slug: 'panama',
      ISO2: 'PA',
      continent: 'North America',
    },
    {
      name: 'Tanzania, United Republic of',
      slug: 'tanzania',
      ISO2: 'TZ',
      continent: 'Africa',
    },
    {
      name: 'Japan',
      slug: 'japan',
      ISO2: 'JP',
      continent: 'Asia',
    },
    {
      name: 'Liechtenstein',
      slug: 'liechtenstein',
      ISO2: 'LI',
      continent: 'Europe',
    },
    {
      name: 'China',
      slug: 'china',
      ISO2: 'CN',
      continent: 'Asia',
    },
    {
      name: 'Monaco',
      slug: 'monaco',
      ISO2: 'MC',
      continent: 'Europe',
    },
    {
      name: 'New Caledonia',
      slug: 'new-caledonia',
      ISO2: 'NC',
      continent: 'Oceania',
    },
    {
      name: 'Spain',
      slug: 'spain',
      ISO2: 'ES',
      continent: 'Europe',
    },
    {
      name: 'Falkland Islands (Malvinas)',
      slug: 'falkland-islands-malvinas',
      ISO2: 'FK',
      continent: 'South America',
    },
    {
      name: 'Gabon',
      slug: 'gabon',
      ISO2: 'GA',
      continent: 'Africa',
    },
    {
      name: 'Maldives',
      slug: 'maldives',
      ISO2: 'MV',
      continent: 'Africa',
    },
    {
      name: 'Saint-Martin (French part)',
      slug: 'saint-martin-french-part',
      ISO2: 'MF',
      continent: 'North America',
    },
    {
      name: 'Iraq',
      slug: 'iraq',
      ISO2: 'IQ',
      continent: 'Asia',
    },
    {
      name: 'Ireland',
      slug: 'ireland',
      ISO2: 'IE',
      continent: 'Europe',
    },
    {
      name: 'Jordan',
      slug: 'jordan',
      ISO2: 'JO',
      continent: 'Asia',
    },
    {
      name: 'Portugal',
      slug: 'portugal',
      ISO2: 'PT',
      continent: 'Europe',
    },
    {
      name: 'Rwanda',
      slug: 'rwanda',
      ISO2: 'RW',
      continent: 'Africa',
    },
    {
      name: 'Sierra Leone',
      slug: 'sierra-leone',
      ISO2: 'SL',
      continent: 'Africa',
    },
    {
      name: 'Guyana',
      slug: 'guyana',
      ISO2: 'GY',
      continent: 'South America',
    },
    {
      name: 'Lesotho',
      slug: 'lesotho',
      ISO2: 'LS',
      continent: 'Africa',
    },
    {
      name: 'Benin',
      slug: 'benin',
      ISO2: 'BJ',
      continent: 'Africa',
    },
    {
      name: 'Hong Kong, SAR China',
      slug: 'hong-kong-sar-china',
      ISO2: 'HK',
      continent: 'Asia',
    },
    {
      name: 'Saint Lucia',
      slug: 'saint-lucia',
      ISO2: 'LC',
      continent: 'North America',
    },
    {
      name: 'Colombia',
      slug: 'colombia',
      ISO2: 'CO',
      continent: 'South America',
    },
    {
      name: 'Switzerland',
      slug: 'switzerland',
      ISO2: 'CH',
      continent: 'Europe',
    },
    {
      name: 'Uruguay',
      slug: 'uruguay',
      ISO2: 'UY',
      continent: 'South America',
    },
    {
      name: 'Egypt',
      slug: 'egypt',
      ISO2: 'EG',
      continent: 'Africa',
    },
    {
      name: 'Kenya',
      slug: 'kenya',
      ISO2: 'KE',
      continent: 'Africa',
    },
    {
      name: 'Peru',
      slug: 'peru',
      ISO2: 'PE',
      continent: 'South America',
    },
    {
      name: 'Cape Verde',
      slug: 'cape-verde',
      ISO2: 'CV',
      continent: 'Africa',
    },
    {
      name: 'Indonesia',
      slug: 'indonesia',
      ISO2: 'ID',
      continent: 'Asia',
    },
    {
      name: 'Zimbabwe',
      slug: 'zimbabwe',
      ISO2: 'ZW',
      continent: 'Africa',
    },
    {
      name: 'Antigua and Barbuda',
      slug: 'antigua-and-barbuda',
      ISO2: 'AG',
      continent: 'North America',
    },
    {
      name: 'Congo (Kinshasa)',
      slug: 'congo-kinshasa',
      ISO2: 'CD',
      continent: 'Africa',
    },
    {
      name: 'Fiji',
      slug: 'fiji',
      ISO2: 'FJ',
      continent: 'Oceania',
    },
    {
      name: 'Isle of Man',
      slug: 'isle-of-man',
      ISO2: 'IM',
      continent: 'Europe',
    },
    {
      name: 'Kazakhstan',
      slug: 'kazakhstan',
      ISO2: 'KZ',
      continent: 'Asia',
    },
    {
      name: 'Swaziland',
      slug: 'swaziland',
      ISO2: 'SZ',
      continent: 'Africa',
    },
    {
      name: 'Austria',
      slug: 'austria',
      ISO2: 'AT',
      continent: 'Europe',
    },
    {
      name: 'French Guiana',
      slug: 'french-guiana',
      ISO2: 'GF',
      continent: 'South America',
    },
    {
      name: 'Netherlands',
      slug: 'netherlands',
      ISO2: 'NL',
      continent: 'Europe',
    },
    {
      name: 'Turkey',
      slug: 'turkey',
      ISO2: 'TR',
      continent: 'Asia',
    },
    {
      name: 'Viet Nam',
      slug: 'vietnam',
      ISO2: 'VN',
      continent: 'Asia',
    },
    {
      name: 'Moldova',
      slug: 'moldova',
      ISO2: 'MD',
      continent: 'Europe',
    },
    {
      name: 'Bulgaria',
      slug: 'bulgaria',
      ISO2: 'BG',
      continent: 'Europe',
    },
    {
      name: 'Ghana',
      slug: 'ghana',
      ISO2: 'GH',
      continent: 'Africa',
    },
    {
      name: 'Jersey',
      slug: 'jersey',
      ISO2: 'JE',
      continent: 'Europe',
    },
    {
      name: 'Slovenia',
      slug: 'slovenia',
      ISO2: 'SI',
      continent: 'Europe',
    },
    {
      name: 'Botswana',
      slug: 'botswana',
      ISO2: 'BW',
      continent: 'Africa',
    },
    {
      name: 'Burkina Faso',
      slug: 'burkina-faso',
      ISO2: 'BF',
      continent: 'Africa',
    },
    {
      name: 'Cayman Islands',
      slug: 'cayman-islands',
      ISO2: 'KY',
      continent: 'North America',
    },
    {
      name: "Côte d'Ivoire",
      slug: 'cote-divoire',
      ISO2: 'CI',
      continent: 'Africa',
    },
    {
      name: 'Gambia',
      slug: 'gambia',
      ISO2: 'GM',
      continent: 'Africa',
    },
    {
      name: 'Barbados',
      slug: 'barbados',
      ISO2: 'BB',
      continent: 'North America',
    },
    {
      name: 'Belize',
      slug: 'belize',
      ISO2: 'BZ',
      continent: 'North America',
    },
    {
      name: 'Guinea-Bissau',
      slug: 'guinea-bissau',
      ISO2: 'GW',
      continent: 'Africa',
    },
    {
      name: 'Luxembourg',
      slug: 'luxembourg',
      ISO2: 'LU',
      continent: 'Europe',
    },
    {
      name: 'Ecuador',
      slug: 'ecuador',
      ISO2: 'EC',
      continent: 'South America',
    },
    {
      name: 'Guinea',
      slug: 'guinea',
      ISO2: 'GN',
      continent: 'Africa',
    },
    {
      name: 'Haiti',
      slug: 'haiti',
      ISO2: 'HT',
      continent: 'North America',
    },
    {
      name: 'Namibia',
      slug: 'namibia',
      ISO2: 'NA',
      continent: 'Africa',
    },
    {
      name: 'Suriname',
      slug: 'suriname',
      ISO2: 'SR',
      continent: 'Africa',
    },
    {
      name: 'Uzbekistan',
      slug: 'uzbekistan',
      ISO2: 'UZ',
      continent: 'Asia',
    },
    {
      name: 'Holy See (Vatican City State)',
      slug: 'holy-see-vatican-city-state',
      ISO2: 'VA',
      continent: 'Europe',
    },
    {
      name: 'Mayotte',
      slug: 'mayotte',
      ISO2: 'YT',
      continent: 'Africa',
    },
    {
      name: 'Singapore',
      slug: 'singapore',
      ISO2: 'SG',
      continent: 'Asia',
    },
    {
      name: 'Solomon Islands',
      slug: 'solomon-islands',
      ISO2: 'SB',
      continent: 'Oceania',
    },
    {
      name: 'Liberia',
      slug: 'liberia',
      ISO2: 'LR',
      continent: 'Africa',
    },
    {
      name: 'Montenegro',
      slug: 'montenegro',
      ISO2: 'ME',
      continent: 'Europe',
    },
    {
      name: 'Latvia',
      slug: 'latvia',
      ISO2: 'LV',
      continent: 'Europe',
    },
    {
      name: 'Mozambique',
      slug: 'mozambique',
      ISO2: 'MZ',
      continent: 'Africa',
    },
    {
      name: 'Senegal',
      slug: 'senegal',
      ISO2: 'SN',
      continent: 'Africa',
    },
    {
      name: 'Serbia',
      slug: 'serbia',
      ISO2: 'RS',
      continent: 'Europe',
    },
    {
      name: 'Belgium',
      slug: 'belgium',
      ISO2: 'BE',
      continent: 'Europe',
    },
    {
      name: 'Croatia',
      slug: 'croatia',
      ISO2: 'HR',
      continent: 'Europe',
    },
    {
      name: 'France',
      slug: 'france',
      ISO2: 'FR',
      continent: 'Europe',
    },
    {
      name: 'Burundi',
      slug: 'burundi',
      ISO2: 'BI',
      continent: 'Africa',
    },
    {
      name: 'Libya',
      slug: 'libya',
      ISO2: 'LY',
      continent: 'Africa',
    },
    {
      name: 'Madagascar',
      slug: 'madagascar',
      ISO2: 'MG',
      continent: 'Africa',
    },
    {
      name: 'Marshall Islands',
      slug: 'marshall-islands',
      ISO2: 'MH',
      continent: 'Oceania',
    },
    {
      name: 'Norway',
      slug: 'norway',
      ISO2: 'NO',
      continent: 'Europe',
    },
    {
      name: 'Oman',
      slug: 'oman',
      ISO2: 'OM',
      continent: 'Asia',
    },
    {
      name: 'Anguilla',
      slug: 'anguilla',
      ISO2: 'AI',
      continent: 'North America',
    },
    {
      name: 'Germany',
      slug: 'germany',
      ISO2: 'DE',
      continent: 'Europe',
    },
    {
      name: 'Mongolia',
      slug: 'mongolia',
      ISO2: 'MN',
      continent: 'Asia',
    },
    {
      name: 'Papua New Guinea',
      slug: 'papua-new-guinea',
      ISO2: 'PG',
      continent: 'Oceania',
    },
    {
      name: 'Saint Vincent and Grenadines',
      slug: 'saint-vincent-and-the-grenadines',
      ISO2: 'VC',
      continent: 'North America',
    },
    {
      name: 'Bangladesh',
      slug: 'bangladesh',
      ISO2: 'BD',
      continent: 'Asia',
    },
    {
      name: 'Lebanon',
      slug: 'lebanon',
      ISO2: 'LB',
      continent: 'Asia',
    },
    {
      name: 'Malta',
      slug: 'malta',
      ISO2: 'MT',
      continent: 'Europe',
    },
    {
      name: 'Algeria',
      slug: 'algeria',
      ISO2: 'DZ',
      continent: 'Africa',
    },
    {
      name: 'Greenland',
      slug: 'greenland',
      ISO2: 'GL',
      continent: 'Europe',
    },
    {
      name: 'Malaysia',
      slug: 'malaysia',
      ISO2: 'MY',
      continent: 'Asia',
    },
    {
      name: 'Saint Kitts and Nevis',
      slug: 'saint-kitts-and-nevis',
      ISO2: 'KN',
      continent: 'North America',
    },
    {
      name: 'Slovakia',
      slug: 'slovakia',
      ISO2: 'SK',
      continent: 'Europe',
    },
    {
      name: 'Brunei Darussalam',
      slug: 'brunei',
      ISO2: 'BN',
      continent: 'Asia',
    },
    {
      name: 'Yemen',
      slug: 'yemen',
      ISO2: 'YE',
      continent: 'Asia',
    },
    {
      name: 'Bosnia and Herzegovina',
      slug: 'bosnia-and-herzegovina',
      ISO2: 'BA',
      continent: 'Europe',
    },
    {
      name: 'Western Sahara',
      slug: 'western-sahara',
      ISO2: 'EH',
      continent: 'Africa',
    },
    {
      name: 'Finland',
      slug: 'finland',
      ISO2: 'FI',
      continent: 'Europe',
    },
    {
      name: 'British Virgin Islands',
      slug: 'british-virgin-islands',
      ISO2: 'VG',
      continent: 'North America',
    },
    {
      name: 'Grenada',
      slug: 'grenada',
      ISO2: 'GD',
      continent: 'North America',
    },
    {
      name: 'Iceland',
      slug: 'iceland',
      ISO2: 'IS',
      continent: 'Europe',
    },
    {
      name: 'Poland',
      slug: 'poland',
      ISO2: 'PL',
      continent: 'Europe',
    },
    {
      name: 'Central African Republic',
      slug: 'central-african-republic',
      ISO2: 'CF',
      continent: 'Africa',
    },
    {
      name: 'Costa Rica',
      slug: 'costa-rica',
      ISO2: 'CR',
      continent: 'North America',
    },
    {
      name: 'Russian Federation',
      slug: 'russia',
      ISO2: 'RU',
      continent: 'Asia',
    },
    {
      name: 'UK',
      slug: 'united-kingdom',
      ISO2: 'GB',
      continent: 'Europe',
    },
    {
      name: 'Czech Republic',
      slug: 'czech-republic',
      ISO2: 'CZ',
      continent: 'Europe',
    },
    {
      name: 'Tajikistan',
      slug: 'tajikistan',
      ISO2: 'TJ',
      continent: 'Asia',
    },
    {
      name: 'Albania',
      slug: 'albania',
      ISO2: 'AL',
      continent: 'Europe',
    },
    {
      name: 'India',
      slug: 'india',
      ISO2: 'IN',
      continent: 'Asia',
    },
    {
      name: 'Qatar',
      slug: 'qatar',
      ISO2: 'QA',
      continent: 'Asia',
    },
    {
      name: 'Réunion',
      slug: 'réunion',
      ISO2: 'RE',
      continent: 'Africa',
    },
    {
      name: 'USA',
      slug: 'united-states',
      ISO2: 'US',
      continent: 'North America',
    },
    {
      name: 'Macao, SAR China',
      slug: 'macao-sar-china',
      ISO2: 'MO',
      continent: 'Asia',
    },
    {
      name: 'San Marino',
      slug: 'san-marino',
      ISO2: 'SM',
      continent: 'Europe',
    },
    {
      name: 'Malawi',
      slug: 'malawi',
      ISO2: 'MW',
      continent: 'Africa',
    },
    {
      name: 'Kyrgyzstan',
      slug: 'kyrgyzstan',
      ISO2: 'KG',
      continent: 'Asia',
    },
    {
      name: 'Romania',
      slug: 'romania',
      ISO2: 'RO',
      continent: 'Europe',
    },
    {
      name: 'Estonia',
      slug: 'estonia',
      ISO2: 'EE',
      continent: 'Europe',
    },
    {
      name: 'Mexico',
      slug: 'mexico',
      ISO2: 'MX',
      continent: 'North America',
    },
    {
      name: 'Saudi Arabia',
      slug: 'saudi-arabia',
      ISO2: 'SA',
      continent: 'Asia',
    },
    {
      name: 'Thailand',
      slug: 'thailand',
      ISO2: 'TH',
      continent: 'Asia',
    },
    {
      name: 'Georgia',
      slug: 'georgia',
      ISO2: 'GE',
      continent: 'Asia',
    },
    {
      name: 'Lithuania',
      slug: 'lithuania',
      ISO2: 'LT',
      continent: 'Europe',
    },
    {
      name: 'Togo',
      slug: 'togo',
      ISO2: 'TG',
      continent: 'Africa',
    },
    {
      name: 'Bolivia',
      slug: 'bolivia',
      ISO2: 'BO',
      continent: 'South America',
    },
    {
      name: 'Israel',
      slug: 'israel',
      ISO2: 'IL',
      continent: 'Asia',
    },
    {
      name: 'Italy',
      slug: 'italy',
      ISO2: 'IT',
      continent: 'Europe',
    },
    {
      name: 'Mali',
      slug: 'mali',
      ISO2: 'ML',
      continent: 'Africa',
    },
    {
      name: 'Andorra',
      slug: 'andorra',
      ISO2: 'AD',
      continent: 'Europe',
    },
    {
      name: 'Bermuda',
      slug: 'bermuda',
      ISO2: 'BM',
      continent: 'North America',
    },
    {
      name: 'Bhutan',
      slug: 'bhutan',
      ISO2: 'BT',
      continent: 'Asia',
    },
    {
      name: 'Greece',
      slug: 'greece',
      ISO2: 'GR',
      continent: 'Europe',
    },
    {
      name: 'Iran, Islamic Republic of',
      slug: 'iran',
      ISO2: 'IR',
      continent: 'Asia',
    },
    {
      name: 'Martinique',
      slug: 'martinique',
      ISO2: 'MQ',
      continent: 'North America',
    },
    {
      name: 'New Zealand',
      slug: 'new-zealand',
      ISO2: 'NZ',
      continent: 'Oceania',
    },
    {
      name: 'Syrian Arab Republic (Syria)',
      slug: 'syria',
      ISO2: 'SY',
      continent: 'Asia',
    },
    {
      name: 'Tunisia',
      slug: 'tunisia',
      ISO2: 'TN',
      continent: 'Africa',
    },
    {
      name: 'Sudan',
      slug: 'sudan',
      ISO2: 'SD',
      continent: 'Africa',
    },
    {
      name: 'Wallis and Futuna Islands',
      slug: 'wallis-and-futuna-islands',
      ISO2: 'WF',
      continent: 'Oceania',
    },
    {
      name: 'Morocco',
      slug: 'morocco',
      ISO2: 'MA',
      continent: 'Africa',
    },
    {
      name: 'Pakistan',
      slug: 'pakistan',
      ISO2: 'PK',
      continent: 'Asia',
    },
    {
      name: 'Myanmar',
      slug: 'myanmar',
      ISO2: 'MM',
      continent: 'Asia',
    },
    {
      name: 'Nicaragua',
      slug: 'nicaragua',
      ISO2: 'NI',
      continent: 'North America',
    },
    {
      name: 'Ukraine',
      slug: 'ukraine',
      ISO2: 'UA',
      continent: 'Europe',
    },
  ],
};
